LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE    := retro
CPU_ARCH        :=

ifeq ($(TARGET_ARCH),arm)
LOCAL_CFLAGS += -DANDROID_ARM -DARM_ARCH
LOCAL_ARM_MODE := arm
CPU_ARCH := arm
HAVE_DYNAREC := 1
endif

ifeq ($(TARGET_ARCH),x86)
LOCAL_CFLAGS +=  -DANDROID_X86
CPU_ARCH := x86_32
HAVE_DYNAREC := 1
endif

#ifeq ($(TARGET_ARCH),mips)
#LOCAL_CFLAGS += -DANDROID_MIPS -D__mips__ -D__MIPSEL__
#endif

CORE_DIR := ..

SOURCES_C   :=
SOURCES_ASM :=


include $(CORE_DIR)/Makefile.common

LOCAL_SRC_FILES := $(SOURCES_C) $(SOURCES_ASM)
LOCAL_CFLAGS += -O2 -DHAVE_MMAP -DNDEBUG -DPC_BUILD -DINLINE=inline -D__LIBRETRO__ -DFRONTEND_SUPPORTS_RGB565 $(INCFLAGS)

include $(BUILD_SHARED_LIBRARY)
