LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE    := retro

ifeq ($(TARGET_ARCH),arm)
LOCAL_CFLAGS += -DANDROID_ARM
LOCAL_ARM_MODE := arm
endif

#ifeq ($(TARGET_ARCH),x86)
#LOCAL_CFLAGS +=  -DANDROID_X86
#endif

#ifeq ($(TARGET_ARCH),mips)
#LOCAL_CFLAGS += -DANDROID_MIPS -D__mips__ -D__MIPSEL__
#endif

CORE_DIR := ..

SOURCES_C   :=
SOURCES_ASM :=

include $(CORE_DIR)/Makefile.common

CPU_ARCH := arm

LOCAL_SRC_FILES := $(SOURCES_C) $(SOURCES_ASM)
LOCAL_CFLAGS += -O2 -DARM_ARCH -DNDEBUG -DINLINE=inline -D__LIBRETRO__ -DFRONTEND_SUPPORTS_RGB565 $(INCFLAGS)

include $(BUILD_SHARED_LIBRARY)
